  
dist:     trusty
sudo:     required

language: c

os:
  - linux

compiler:
  - gcc

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
  - sudo apt-get install cppcheck
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtest-dev valgrind cmake
  - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
  - sudo tar xf release-1.7.0.tar.gz
  - cd googletest-release-1.7.0
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make
  - sudo cp -a include/gtest /usr/include
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  - which valgrind
  - cd "${TRAVIS_BUILD_DIR}"

script:
  - cppcheck waybill_spliter/waybill_split.h waybill_spliter/console_communication.h waybill_spliter/product_struct.h waybill_spliter/waybill_split.c waybill_spliter/console_communication.c
  - mkdir build
  - cd build
  - ls
  - cmake ../
  - ls ../Google_tests
  - ls
  - cd ../Google_tests
  - ls
  - valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --leak-resolution=med  --track-origins=yes ./tests.cpp
  - sudo apt-get install lib32z1
  - valgrind Google_tests/Google_Tests_run
  - valgrind --leak-check=full -q ../Google_tests/tests.cpp
  - valgrind ../cmake-build-debug/Google_tests/Google_Tests_run
  - cd ../Google_tests
  - ls
  - valgrind tests
  - chmod 775 ./tests.cpp
  - valgrind ./tests
  - make prog
  - cat Google_tests/tests | valgrind ./prog >> test_res.dat
