name: cppcheck-action
on: 
  push:
    branches: 
      - master
        - code
  pull_request:
    branches:
      - master
        - code


jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: deep5050/cppcheck-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          github_username: "labzunova"
          github_email: "dasha.labzunova@mail.ru"
          commit_msg: "."
